Set up SOWIN_NOT_DLL for the sowin-config script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5535,9 +5535,7 @@ fi
 if $sim_ac_build_library; then
 if $BUILD_WITH_MSVC; then
   if $SOWIN_STATIC; then
-    :
-    CPPFLAGS="$CPPFLAGS -DSOWIN_NOT_DLL"
-    # SOWIN_EXTRA_CPPFLAGS is set up further down
+    SOWIN_EXTRA_CPPFLAGS="$SOWIN_EXTRA_CPPFLAGS -DSOWIN_NOT_DLL"
   else
     CPPFLAGS="-DSOWIN_MAKE_DLL $CPPFLAGS"
     SOWIN_EXTRA_CPPFLAGS="$SOWIN_EXTRA_CPPFLAGS -DSOWIN_DLL"
@@ -5554,7 +5552,7 @@ fi
 
     LIBFLAGS="-LIB"
     LIBFLAGS="$LIBFLAGS /OUT:sowin$SOWIN_MAJOR_VERSION$SUFFIX.lib"
-    SOWIN_EXTRA_CPPFLAGS="-I$includedir -DSOWIN_NOT_DLL"
+    SOWIN_EXTRA_CPPFLAGS="-I$includedir"
     SOWIN_EXTRA_LDFLAGS="-L$libdir"
     SOWIN_EXTRA_LIBS=
   else
@@ -5702,7 +5700,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5705: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5703: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5878,7 +5876,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5881: error: ambiguous option: $1
+    { { echo "$as_me:5879: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5897,7 +5895,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5900: error: unrecognized option: $1
+  -*) { { echo "$as_me:5898: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5962,7 +5960,7 @@ do
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "src/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/config.h" ;;
-  *) { { echo "$as_me:5965: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5963: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -6248,7 +6246,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:6251: creating $ac_file" >&5
+    { echo "$as_me:6249: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -6266,7 +6264,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6269: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6267: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6279,7 +6277,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6282: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6280: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6340,7 +6338,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:6343: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:6341: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -6351,7 +6349,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6354: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6352: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6364,7 +6362,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6367: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6365: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6481,7 +6479,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6484: $ac_file is unchanged" >&5
+      { echo "$as_me:6482: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
