Bugfix.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5505,15 +5505,19 @@ exec_prefix=$sim_ac_save_exec_prefix
 
 SOWIN_STATIC=false
 
-case $enable_static in
-yes | true)  SOWIN_STATIC=true;;
-*)           SOWIN_STATIC=false;;
-esac
+if test x${enable_shared+set} = xset; then
+  case $enable_shared in
+  yes | true)  SOWIN_STATIC=false ;;
+  *)           SOWIN_STATIC=true ;;
+  esac
+fi
 
-case $enable_shared in
-yes | true)  SOWIN_STATIC=false ;;
-*)           SOWIN_STATIC=true ;;
-esac
+if test x${enable_static+set} = xset; then
+  case $enable_static in
+  yes | true)  SOWIN_STATIC=true ;;
+  *)           SOWIN_STATIC=false ;;
+  esac
+fi
 
 LIBFLAGS=
 
@@ -5698,7 +5702,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5701: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5705: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5874,7 +5878,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5877: error: ambiguous option: $1
+    { { echo "$as_me:5881: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5893,7 +5897,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5896: error: unrecognized option: $1
+  -*) { { echo "$as_me:5900: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5958,7 +5962,7 @@ do
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "src/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/config.h" ;;
-  *) { { echo "$as_me:5961: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5965: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -6244,7 +6248,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:6247: creating $ac_file" >&5
+    { echo "$as_me:6251: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -6262,7 +6266,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6265: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6269: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6275,7 +6279,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6278: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6282: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6336,7 +6340,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:6339: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:6343: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -6347,7 +6351,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6350: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6354: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6360,7 +6364,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6363: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6367: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6477,7 +6481,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6480: $ac_file is unchanged" >&5
+      { echo "$as_me:6484: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
